spring:
  config:
    activate:
      on-profile: test

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 0.0

logging:
  level:
    root: WARN
    com.portfolio: INFO
