spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
    env:
      access: none
    loggers:
      access: none
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}

logging:
  level:
    root: WARN
    com.portfolio: INFO
